apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue-app
spec:
  replicas: 2
  selector: 
    matchLabels:
      name: canary
  template:
    metadata:
      labels:
        name: canary
    spec:
      containers:
      - name: mercedes
        image: arunawsdevops/car-image:4.0
        ports:
        - containerPort: 80
          protocol: TCP
